account: UA-4125947-4
premium: false
domain_mode: 0
cross_domains: ''
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\n/admin/*\n/batch\n/node/add*\n/node/*/*\n/user/*/*"
  user_role_mode: 0
  user_role_roles: {  }
  user_account_mode: 0
track:
  outbound: true
  mailto: true
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls|xml|z|zip'
  colorbox: true
  linkid: false
  urlfragments: false
  userid: false
  messages: {  }
  site_search: false
  adsense: false
  displayfeatures: true
privacy:
  anonymizeip: false
custom:
  dimension: {  }
  metric: {  }
codesnippet:
  create: {  }
  before: ''
  after: ''
translation_set: false
cache: false
debug: false
_core:
  default_config_hash: HD-kJquDfx3JureBUmIIt_ADNReD_jLvKg4fwKISoJs
